[package]
name = "fluentlang-cli"
authors = ["Actro25"]
description = "Nothing"
version = "0.1.0"
edition = "2024"

[dependencies]
fluentlang-core = { path = "../fluentlang-core" }
fluentlang-api = { path = "../fluentlang-api" }
clap = { workspace = true, features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }